services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infosys
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "/mnt/c/Users/rober/OneDrive/Escritorio/datos elec:/datos"


volumes:
  postgres_data:
