import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

// Datos de secciones proporcionados
const seccionesData = [
  { nombre: "1", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "2", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "3", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "4", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "5", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "6", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "7", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "8", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "9", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "10", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "11", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "12", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "13", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "14", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "15", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "16", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "17", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "18", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "19", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "20", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "21", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "22", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "23", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "24", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "25", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "26", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "27", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "28", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "29", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "30", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "31", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "32", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "33", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "34", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "35", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "36", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "37", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "38", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "39", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "40", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "41", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "42", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "43", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "44", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "45", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "46", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "47", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "48", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "49", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "50", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "51", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "52", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "53", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "54", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "55", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "56", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "57", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "58", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "59", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "60", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "61", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "62", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "67", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "68", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "69", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "70", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "71", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "72", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "73", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "74", distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: "75", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "76", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "77", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "78", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "79", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "80", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "81", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "82", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "83", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "84", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "85", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "86", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "87", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "88", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "89", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "90", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "91", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "92", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "93", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "94", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "95", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "96", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "97", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "98", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "99", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "101", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "102", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "103", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "105", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "107", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "108", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "109", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "110", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "111", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "112", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "113", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "114", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "115", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "116", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "117", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "118", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "119", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "120", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "496", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "497", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "498", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "499", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "500", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "501", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "502", distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: "121", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "122", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "123", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "124", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "125", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "126", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "127", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "128", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "129", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "130", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "131", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "132", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "133", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "134", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "135", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "136", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "137", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "138", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "139", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "140", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "141", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "142", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "143", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "144", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "145", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "146", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "147", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "148", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "149", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "150", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "151", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "152", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "153", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "154", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "155", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "156", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "157", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "158", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "159", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "160", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "161", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "162", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "163", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "164", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "165", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "166", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "167", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "168", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "169", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "170", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "171", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "172", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "173", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "174", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "175", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "176", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "177", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "178", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "179", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "180", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "181", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "182", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "183", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "184", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "185", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "186", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "187", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "188", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "189", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "190", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "191", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "192", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "193", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "194", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "195", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "196", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "197", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "198", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "199", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "200", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "201", distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: "202", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "203", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "204", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "205", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "207", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "208", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "209", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "210", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "211", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "212", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "213", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "214", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "215", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "216", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "217", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "218", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "219", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "220", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "221", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "222", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "223", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "224", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "225", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "226", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "227", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "228", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "229", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "230", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "231", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "232", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "233", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "234", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "235", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "236", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "237", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "238", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "239", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "240", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "241", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "242", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "243", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "244", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "245", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "246", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "247", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "248", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "249", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "250", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "251", distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: "254", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "255", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "256", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "257", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "258", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "259", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "260", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "261", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "262", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "263", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "264", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "265", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "266", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "267", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "268", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "269", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "270", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "271", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "272", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "273", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "274", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "276", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "277", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "278", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "280", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "281", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "282", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "283", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "284", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "286", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "287", distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: "288", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "289", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "348", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "349", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "350", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "440", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "441", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "442", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "443", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "444", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "445", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "446", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "447", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "448", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "449", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "450", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "451", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "452", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "453", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "454", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "455", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "456", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "457", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "458", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "459", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "460", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "461", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "462", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "463", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "464", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "465", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "466", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "467", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "468", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "469", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "470", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "471", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "472", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "473", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "474", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "475", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "476", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "477", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "478", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "479", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "480", distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: "481", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "482", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "483", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "484", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "485", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "486", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "487", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "488", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "489", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "490", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "491", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "492", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "493", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "494", distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: "495", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "542", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "543", distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: "338", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "339", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "340", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "341", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "342", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "343", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "344", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "345", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "346", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "347", distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: "290", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "291", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "292", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "293", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "294", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "295", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "296", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "297", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "299", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "300", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "302", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "303", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "304", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "305", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "306", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "307", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "308", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "309", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "310", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "311", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "313", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "315", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "316", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "317", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "318", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "319", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "320", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "321", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "322", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "323", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "324", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "325", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "326", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "327", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "328", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "329", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "331", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "333", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "334", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "335", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "336", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "351", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "352", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "354", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "355", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "356", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "357", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "358", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "359", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "360", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "361", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "362", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "363", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "364", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "365", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "366", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "367", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "368", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "369", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "370", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "371", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "372", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "373", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "374", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "375", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "376", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "377", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "378", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "379", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "380", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "381", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "382", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "383", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "384", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "385", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "386", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "387", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "388", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "389", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "390", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "391", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "392", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "393", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "394", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "395", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "396", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "397", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "398", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "399", distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: "400", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "401", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "402", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "403", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "404", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "405", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "406", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "407", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "408", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "409", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "410", distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: "411", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "413", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "414", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "415", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "416", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "417", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "418", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "419", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "420", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "421", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "422", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "423", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "424", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "425", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "426", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "427", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "428", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "429", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "430", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "431", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "432", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "433", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "434", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "435", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "436", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "437", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "438", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "439", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "503", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "504", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "505", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "506", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "507", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "508", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "509", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "510", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "511", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "512", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "513", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "514", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "515", distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: "516", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "517", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "518", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "519", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "520", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "521", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "522", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "523", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "524", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "525", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "526", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "527", distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: "528", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "529", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "530", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "531", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "532", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "533", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "534", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "535", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "536", distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: "537", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "538", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "539", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "540", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "541", distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: "544", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "545", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "546", distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: "547", distritoLocalId: 7, distritoFederalId: 2 },
]

export async function main() {
  console.log("Iniciando seed de secciones electorales específicas...")

  // Verificar y crear distritos locales si no existen
  const distritosLocales = await prisma.distritoLocal.findMany()
  if (distritosLocales.length === 0) {
    console.log("No se encontraron distritos locales. Creando distritos locales...")
    await prisma.distritoLocal.createMany({
      data: [
        { nombre: "1" },
        { nombre: "2" },
        { nombre: "3" },
        { nombre: "4" },
        { nombre: "5" },
        { nombre: "6"},
        { nombre: "7" },
        { nombre: "8" },
        { nombre: "9" },
        { nombre: "10" },
        { nombre: "11" },
        { nombre: "12" },
        { nombre: "13" },
        { nombre: "14" },
        { nombre: "15" },
        { nombre: "16" },      ],
    })
    console.log("Distritos locales creados exitosamente.")
  } else {
    console.log(`Se encontraron ${distritosLocales.length} distritos locales existentes.`)
  }

  // Verificar y crear distritos federales si no existen
  const distritosFederales = await prisma.distritoFederal.findMany()
  if (distritosFederales.length === 0) {
    console.log("No se encontraron distritos federales. Creando distritos federales...")
    await prisma.distritoFederal.createMany({
      data: [
        { nombre: "1" },
        { nombre: "2" },      ],
    })
    console.log("Distritos federales creados exitosamente.")
  } else {
    console.log(`Se encontraron ${distritosFederales.length} distritos federales existentes.`)
  }

  // Verificar si ya existen secciones
  const seccionesExistentes = await prisma.seccion.count()
  if (seccionesExistentes > 0) {
    console.log(`Ya existen ${seccionesExistentes} secciones en la base de datos.`)
    console.log("¿Deseas continuar y crear más secciones? Si es así, ejecuta con la opción --force")

    // Si no se proporciona la opción --force, salir
    if (!process.argv.includes("--force")) {
      console.log("Saliendo sin crear nuevas secciones.")
      return
    }
  }

  // Crear secciones
  console.log("Creando secciones electorales específicas...")

  // Crear las secciones en la base de datos
  const seccionesCreadas = await prisma.seccion.createMany({
    data: seccionesData,
    skipDuplicates: true, // Omitir duplicados si los hay
  })

  console.log(`Se crearon ${seccionesCreadas.count} secciones electorales exitosamente.`)
}


