import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function main() {
  console.log(
    "Iniciando seed de secciones electorales con datos específicos..."
  );

  // Verificar y crear municipios si no existen
  const municipios = await prisma.municipio.findMany();
  if (municipios.length === 0) {
    console.log("No se encontraron municipios. Creando municipios...");
    await prisma.municipio.createMany({
      data: [
        { nombre: "Comondu" },
        { nombre: "Mulege" },
        { nombre: "La Paz" },
        { nombre: "Los Cabos" },
        { nombre: "Loreto" },
      ],
    });
    console.log("Municipios creados exitosamente.");
  } else {
    console.log(`Se encontraron ${municipios.length} municipios existentes.`);
  } 
    // Verificar y crear distritos locales si no existen
  const distritosLocales = await prisma.distritoLocal.findMany();
  if (distritosLocales.length === 0) {
    console.log(
      "No se encontraron distritos locales. Creando distritos locales..."
    );
    await prisma.distritoLocal.createMany({
      data: [
        { nombre: "2" },
        { nombre: "1" },
        { nombre: "3" },
        { nombre: "4" },
        { nombre: "5" },
        { nombre: "6" },
        { nombre: "7" },
        { nombre: "8" },
        { nombre: "9" },
        { nombre: "10" },
        { nombre: "11" },
        { nombre: "12" },
        { nombre: "13" },
        { nombre: "14" },
        { nombre: "15" },
        { nombre: "16" },
      ],
    });
    console.log("Distritos locales creados exitosamente.");
  } else {
    console.log(
      `Se encontraron ${distritosLocales.length} distritos locales existentes.`
    );
  }

  // Verificar y crear distritos federales si no existen
  const distritosFederales = await prisma.distritoFederal.findMany();
  if (distritosFederales.length === 0) {
    console.log(
      "No se encontraron distritos federales. Creando distritos federales..."
    );
    await prisma.distritoFederal.createMany({
      data: [{ nombre: "1" }, { nombre: "2" }],
    });
    console.log("Distritos federales creados exitosamente.");
  } else {
    console.log(
      `Se encontraron ${distritosFederales.length} distritos federales existentes.`
    );
  }

  // Verificar si ya existen secciones
  const seccionesExistentes = await prisma.seccion.count();
  if (seccionesExistentes > 0) {
    console.log(
      `Ya existen ${seccionesExistentes} secciones en la base de datos.`
    );
    console.log(
      "¿Deseas continuar y crear más secciones? Si es así, ejecuta con la opción --force"
    );

    // Si no se proporciona la opción --force, salir
    if (!process.argv.includes("--force")) {
      console.log("Saliendo sin crear nuevas secciones.");
      return;
    }
  }

  // Obtener los IDs de los municipios, distritos locales y federales
  const municipiosMap = new Map();
  const distritosLocalesMap = new Map();
  const distritosFederalesMap = new Map();

  const municipiosActuales = await prisma.municipio.findMany();
  const distritosLocalesActuales = await prisma.distritoLocal.findMany();
  const distritosFederalesActuales = await prisma.distritoFederal.findMany();

  municipiosActuales.forEach((m) => municipiosMap.set(m.nombre, m.id));
  distritosLocalesActuales.forEach((d) =>
    distritosLocalesMap.set(d.nombre, d.id)
  );
  distritosFederalesActuales.forEach((d) =>
    distritosFederalesMap.set(d.nombre, d.id)
  );

  // Datos específicos de secciones
  const seccionesData = [
  { nombre: 1, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 2, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 3, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 4, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 5, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 6, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 7, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 8, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 9, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 10, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 11, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 12, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 13, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 14, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 15, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 16, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 17, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 18, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 19, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 20, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 21, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 22, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 23, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 24, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 25, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 26, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 27, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 28, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 29, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 30, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 31, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 32, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 33, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 34, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 35, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 36, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 37, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 38, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 39, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 40, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 41, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 42, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 43, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 44, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 45, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 46, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 47, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 48, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 49, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 50, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 51, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 52, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 53, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 54, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 55, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 56, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 57, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 58, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 59, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 60, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 61, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 62, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 67, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 68, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 69, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 70, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 71, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 72, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 73, municipioId: 1, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 74, municipioId: 1, distritoLocalId: 10, distritoFederalId: 1 },
  { nombre: 75, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 76, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 77, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 78, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 79, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 80, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 81, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 82, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 83, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 84, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 85, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 86, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 87, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 88, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 89, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 90, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 91, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 92, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 93, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 94, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 95, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 96, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 97, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 98, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 99, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 101, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 102, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 103, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 105, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 107, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 108, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 109, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 110, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 111, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 112, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 113, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 114, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 115, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 116, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 117, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 118, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 119, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 120, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 121, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 122, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 123, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 124, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 125, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 126, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 127, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 128, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 129, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 130, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 131, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 132, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 133, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 134, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 135, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 136, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 137, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 138, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 139, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 140, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 141, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 142, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 143, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 144, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 145, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 146, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 147, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 148, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 149, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 150, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 151, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 152, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 153, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 154, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 155, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 156, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 157, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 158, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 159, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 160, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 161, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 162, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 163, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 164, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 165, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 166, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 167, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 168, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 169, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 170, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 171, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 172, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 173, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 174, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 175, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 176, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 177, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 178, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 179, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 180, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 181, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 182, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 183, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 184, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 185, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 186, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 187, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 188, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 189, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 190, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 191, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 192, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 193, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 194, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 195, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 196, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 197, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 198, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 199, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 200, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 201, municipioId: 3, distritoLocalId: 2, distritoFederalId: 1 },
  { nombre: 202, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 203, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 204, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 205, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 207, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 208, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 209, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 210, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 211, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 212, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 213, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 214, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 215, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 216, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 217, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 218, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 219, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 220, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 221, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 222, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 223, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 224, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 225, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 226, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 227, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 228, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 229, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 230, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 231, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 232, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 233, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 234, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 235, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 236, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 237, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 238, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 239, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 240, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 241, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 242, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 243, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 244, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 245, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 246, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 247, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 248, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 249, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 250, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 251, municipioId: 3, distritoLocalId: 15, distritoFederalId: 1 },
  { nombre: 254, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 255, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 256, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 257, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 258, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 259, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 260, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 261, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 262, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 263, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 264, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 265, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 266, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 267, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 268, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 269, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 270, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 271, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 272, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 273, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 274, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 276, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 277, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 278, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 280, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 281, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 282, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 283, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 284, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 286, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 287, municipioId: 3, distritoLocalId: 6, distritoFederalId: 1 },
  { nombre: 288, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 289, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 290, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 291, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 292, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 293, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 294, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 295, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 296, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 297, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 299, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 300, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 302, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 303, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 304, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 305, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 306, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 307, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 308, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 309, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 310, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 311, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 313, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 315, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 316, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 317, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 318, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 319, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 320, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 321, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 322, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 323, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 324, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 325, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 326, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 327, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 328, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 329, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 331, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 333, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 334, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 335, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 336, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 338, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 339, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 340, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 341, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 342, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 343, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 344, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 345, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 346, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 347, municipioId: 5, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 348, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 349, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 350, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 351, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 352, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 354, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 355, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 356, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 357, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 358, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 359, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 360, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 361, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 362, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 363, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 364, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 365, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 366, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 367, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 368, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 369, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 370, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 371, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 372, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 373, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 374, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 375, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 376, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 377, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 378, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 379, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 380, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 381, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 382, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 383, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 384, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 385, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 386, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 387, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 388, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 389, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 390, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 391, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 392, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 393, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 394, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 395, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 396, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 397, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 398, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 399, municipioId: 4, distritoLocalId: 9, distritoFederalId: 2 },
  { nombre: 400, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 401, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 402, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 403, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 404, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 405, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 406, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 407, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 408, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 409, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 410, municipioId: 4, distritoLocalId: 8, distritoFederalId: 2 },
  { nombre: 411, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 413, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 414, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 415, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 416, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 417, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 418, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 419, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 420, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 421, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 422, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 423, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 424, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 425, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 426, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 427, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 428, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 429, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 430, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 431, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 432, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 433, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 434, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 435, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 436, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 437, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 438, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 439, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 440, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 441, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 442, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 443, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 444, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 445, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 446, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 447, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 448, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 449, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 450, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 451, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 452, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 453, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 454, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 455, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 456, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 457, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 458, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 459, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 460, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 461, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 462, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 463, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 464, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 465, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 466, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 467, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 468, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 469, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 470, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 471, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 472, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 473, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 474, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 475, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 476, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 477, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 478, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 479, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 480, municipioId: 3, distritoLocalId: 3, distritoFederalId: 1 },
  { nombre: 481, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 482, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 483, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 484, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 485, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 486, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 487, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 488, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 489, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 490, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 491, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 492, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 493, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 494, municipioId: 3, distritoLocalId: 5, distritoFederalId: 1 },
  { nombre: 495, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 496, municipioId: 2, distritoLocalId: 13, distritoFederalId: 1 },
  { nombre: 497, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 498, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 499, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 500, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 501, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 502, municipioId: 2, distritoLocalId: 14, distritoFederalId: 1 },
  { nombre: 503, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 504, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 505, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 506, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 507, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 508, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 509, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 510, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 511, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 512, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 513, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 514, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 515, municipioId: 4, distritoLocalId: 1, distritoFederalId: 2 },
  { nombre: 516, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 517, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 518, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 519, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 520, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 521, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 522, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 523, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 524, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 525, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 526, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 527, municipioId: 4, distritoLocalId: 16, distritoFederalId: 2 },
  { nombre: 528, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 529, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 530, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 531, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 532, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 533, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 534, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 535, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 536, municipioId: 4, distritoLocalId: 11, distritoFederalId: 2 },
  { nombre: 537, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 538, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 539, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 540, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 541, municipioId: 4, distritoLocalId: 12, distritoFederalId: 2 },
  { nombre: 542, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 543, municipioId: 3, distritoLocalId: 4, distritoFederalId: 1 },
  { nombre: 544, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 545, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 546, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 },
  { nombre: 547, municipioId: 4, distritoLocalId: 7, distritoFederalId: 2 }
];

  console.log(`Intentando crear ${seccionesData.length} secciones...`);

  // Crear las secciones en la base de datos
  for (const seccion of seccionesData) {
    try {
      await prisma.seccion.create({
        data: seccion,
      });
    } catch (error) {
      console.error(`Error al crear la sección ${seccion.nombre}:`, error);
    }
  }

  // Verificar y crear casillas si no existen
  const casillas = await prisma.casilla.findMany();
  if (casillas.length === 0) {
    console.log("No se encontraron casillas. Creando casillas...");
    const numeros = [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
      33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
      67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
      97, 98, 99, 101, 102, 103, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 496, 497, 498,
      499, 500, 501, 502, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
      141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
      165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
      189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 207, 208, 209, 210, 211, 212, 213,
      214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237,
      238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263,
      264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 276, 277, 278, 280, 281, 282, 283, 284, 286, 287, 288, 289, 348,
      349, 350, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461,
      462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485,
      486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 542, 543, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 290, 291,
      292, 293, 294, 295, 296, 297, 299, 300, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 313, 315, 316, 317, 318, 319,
      320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 331, 333, 334, 335, 336, 351, 352, 354, 355, 356, 357, 358, 359, 360,
      361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384,
      385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408,
      409, 410, 411, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433,
      434, 435, 436, 437, 438, 439, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520,
      521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 544, 545, 546,
      547
    ];
    for (const numero of numeros) {
      const casillaNueva = { 
        numero: `${numero.toString()}`,
        direccion: "", 
        seccionId: Number(numero) };
      try {
        console.log(casillaNueva)
        await prisma.casilla.create({          
          data: casillaNueva,
        });
        console.log(`Casilla ${casillaNueva.numero} creada exitosamente.`);
      } catch (error) {
        console.error(`Error al crear la casilla ${casillaNueva.numero}:`, error);
      }
    }
    }

  console.log("Seed de secciones completado exitosamente.");

  
}

